apiVersion: batch/v1
kind: CronJob
metadata:
  name: datasource-setup-cronjob
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      generateName: datasource-setup-
    spec:
      parallelism: 1
      completions: 1
      suspend: false
      template:
        spec:
          serviceAccountName: grafana-thanos
          restartPolicy: Never
          containers:
            - name: datasource-setup-script
              image: ubi8-minimal:latest
              args:
                - /script/script.sh
              resources:
                limits:
                  memory: "128Mi"
                  cpu: "500m"
              volumeMounts:
                - mountPath: /script
                  name: script-cm
                - mountPath: /var/run/secrets/tokens
                  name: thanos-token
          volumes:
            - name: script-cm
              configMap:
                defaultMode: 0777
                name: datasource-setup-script
            - name: thanos-token
              projected:
                sources:
                  - serviceAccountToken:
                      path: thanos-token
                      expirationSeconds: 3600
