apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-monitoring
resources:
  - ../../base/team
  - ../../base/grafana/operator
  - grafana-cluster-monitoring-view.yaml
  - ../../base/grafana/instance
  - ../../base/grafana/dashboards
patches:
  - target:
      kind: Namespace
      name: team-x
    patch: |-
      - op: replace
        path: /metadata/name
        value: grafana-monitoring
  - target:
      kind: OperatorGroup
      name: self
    patch: |-
      - op: add
        path: /spec/targetNamespaces/-
        value: grafana-monitoring
  - target:
      kind: GrafanaDataSource
      name: thanos
    # oc sa get-token grafana-thanos
    patch: |-
      - op: replace
        path: /spec/datasources/0/secureJsonData/httpHeaderValue1
        value: Bearer eyJhbGciO...
  - target:
      kind: Grafana
      name: grafana
    patch: |-
      - op: add
        path: /spec/containers/0/args/-
        value: '-openshift-sar={"resource": "namespaces", "verb": "get"}'
